# Generated by Django 6.0.2 on 2026-06-13 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('original_file', models.FileField(upload_to='presentations/original/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='presentations/pdf/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=20)),
                ('total_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('conversion_status', models.CharField(default='pending', max_length=20)),
                ('conversion_error', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PresentationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('next_count', models.PositiveIntegerField(default=0)),
                ('prev_count', models.PositiveIntegerField(default=0)),
                ('total_actions', models.PositiveIntegerField(default=0)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentations.presentation')),
            ],
        ),
        migrations.CreateModel(
            name='GestureActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('slide_number', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentations.presentationsession')),
            ],
        ),
    ]
